[package]
name = "blockchain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { default-features = false, version = "2.2.0", features = ["derive"] }
sha2 = { default-features = false, version = "0.9.6" }
hex = { version = "0.4.3" }
